### PR TITLE
Adding update support for Nexus 5X devices

### PR DESCRIPTION
**Pull request by kopatropa**
I added support for creating update packages for Nexus 5X devices resolving issue #13 
- The update-binary is taken from https://builds.copperhead.co/builds/bullhead-ota_update-2016.11.27.21.33.03.zip
- The extras/bullhead/convert-factory.py was created using https://github.com/CopperheadOS/device_lge_bullhead/blob/nougat-mr0.5-release/releasetools.py and extras/angler/convert-factory.py as a reference
- The extras/blobs/update-binary and extras/metadata files have been moved to to the device-specific extras/angler folder
- The update.sh has been modified to use the particular device-specific metadata and update-binary files
- Added the python command in the update.sh

I successfully tested this upgrading from 2016.11.21.18.36.19 to 2016.11.27.21.33.03

### CODE REVIEW

**Comment by patcon** [comment]
Cool :)

Larger question (not specific to this work), but is there an argument for not version-controlling `update-binary`, and instead taking it from the copperhead zip on the fly (which we've presumably just run checksums against anyhow? Then one less blob ppl need to check provenance on

**Comment by kopatropa** [comment]
You've got a point there. Maybe we can have some symbolic link to https://github.com/CopperheadOS/device_lge_bullhead/blob/nougat-mr0.5-release/update-binary in the repository? I'm new to Github and don't know if/how this is possible. However such a reference might need to be updated when the CopperheadOS branch changes to nougat-mr1-release and nougat-mr2-release.

**Comment by BenBaltz** [comment]
The update binary in the 5X zip & 6P zip are the same.

**Comment by mikeperry-tor** [comment]
Thanks so much. I don't have a Nexus 5X to test on, so I'm going to take this as it is. I will try updating the binary to be a symlink in a follow-on commit.

**Comment by BenBaltz** [comment]
Have you tested updating a 6P using the current update format @mikeperry-tor ?

**Comment by kopatropa** [comment]
Just to clarify: I tested the 5X update using the update-binary from the current bullhead-update zip file which is the same as the one found under https://github.com/CopperheadOS/device_lge_bullhead/blob/nougat-mr0.5-release/update-binary but which is NOT the same as the one which is in this repository and which is now in the extras/angler directory.

**Comment by BenBaltz** [comment]
@kopatropa I've done a lot of Android development and can assure you that there is no difference in the update-binaries. That same update binary will work on hundreds of devices.

**Comment by neuhaus** [comment]
@kopatropa Great! Did the releasetools.py change in important ways from nougat-mr0.5 to nougat-mr1?

**Pull request merged**
